### ISSUE TITLE
Getting "Unexpected exception importing component custom_components.garmin_connect" after 9.3 update

### ISSUE THREAD

**Issue by merc4derp** [cyberjunky/home-assistant-garmin_connect#105]
2 errors in the log, here's the tracebacks:

`Logger: homeassistant.setup
Source: loader.py:826
First occurred: 14:43:02 (1 occurrences)
Last logged: 14:43:02

Setup failed for custom integration garmin_connect: Unable to import component: Exception importing custom_components.garmin_connect
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/loader.py", line 818, in get_component
    ComponentProtocol, importlib.import_module(self.pkg_path)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/config/custom_components/garmin_connect/__init__.py", line 8, in <module>
    from garminconnect import (
  File "/usr/local/lib/python3.11/site-packages/garminconnect/__init__.py", line 9, in <module>
    import garth
  File "/usr/local/lib/python3.11/site-packages/garth/__init__.py", line 1, in <module>
    from .data import HRVData, SleepData
  File "/usr/local/lib/python3.11/site-packages/garth/data/__init__.py", line 3, in <module>
    from .hrv import HRVData
  File "/usr/local/lib/python3.11/site-packages/garth/data/hrv.py", line 6, in <module>
    from .. import http
  File "/usr/local/lib/python3.11/site-packages/garth/http.py", line 10, in <module>
    from . import sso
  File "/usr/local/lib/python3.11/site-packages/garth/sso.py", line 11, in <module>
    from .auth_tokens import OAuth1Token, OAuth2Token
  File "/usr/local/lib/python3.11/site-packages/garth/auth_tokens.py", line 8, in <module>
    @dataclass
     ^^^^^^^^^
  File "pydantic/dataclasses.py", line 231, in pydantic.dataclasses.dataclass
  File "pydantic/dataclasses.py", line 224, in pydantic.dataclasses.dataclass.wrap
  File "pydantic/dataclasses.py", line 347, in pydantic.dataclasses._add_pydantic_validation_attributes
  File "pydantic/dataclasses.py", line 400, in pydantic.dataclasses.create_pydantic_model_from_dataclass
  File "pydantic/main.py", line 1026, in pydantic.main.create_model
  File "pydantic/main.py", line 186, in pydantic.main.ModelMetaclass.__new__
TypeError: Argument 'bases' has incorrect type (expected list, got tuple)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 215, in _async_setup_component
    component = integration.get_component()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 826, in get_component
    raise ImportError(f"Exception importing {self.pkg_path}") from err
ImportError: Exception importing custom_components.garmin_connect
`
`This error originated from a custom integration.

Logger: homeassistant.loader
Source: custom_components/garmin_connect/__init__.py:8
Integration: garmin_connect (documentation, issues)
First occurred: 14:43:02 (1 occurrences)
Last logged: 14:43:02

Unexpected exception importing component custom_components.garmin_connect
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/loader.py", line 818, in get_component
    ComponentProtocol, importlib.import_module(self.pkg_path)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/config/custom_components/garmin_connect/__init__.py", line 8, in <module>
    from garminconnect import (
  File "/usr/local/lib/python3.11/site-packages/garminconnect/__init__.py", line 9, in <module>
    import garth
  File "/usr/local/lib/python3.11/site-packages/garth/__init__.py", line 1, in <module>
    from .data import HRVData, SleepData
  File "/usr/local/lib/python3.11/site-packages/garth/data/__init__.py", line 3, in <module>
    from .hrv import HRVData
  File "/usr/local/lib/python3.11/site-packages/garth/data/hrv.py", line 6, in <module>
    from .. import http
  File "/usr/local/lib/python3.11/site-packages/garth/http.py", line 10, in <module>
    from . import sso
  File "/usr/local/lib/python3.11/site-packages/garth/sso.py", line 11, in <module>
    from .auth_tokens import OAuth1Token, OAuth2Token
  File "/usr/local/lib/python3.11/site-packages/garth/auth_tokens.py", line 8, in <module>
    @dataclass
     ^^^^^^^^^
  File "pydantic/dataclasses.py", line 231, in pydantic.dataclasses.dataclass
  File "pydantic/dataclasses.py", line 224, in pydantic.dataclasses.dataclass.wrap
  File "pydantic/dataclasses.py", line 347, in pydantic.dataclasses._add_pydantic_validation_attributes
  File "pydantic/dataclasses.py", line 400, in pydantic.dataclasses.create_pydantic_model_from_dataclass
  File "pydantic/main.py", line 1026, in pydantic.main.create_model
  File "pydantic/main.py", line 186, in pydantic.main.ModelMetaclass.__new__
TypeError: Argument 'bases' has incorrect type (expected list, got tuple)
`

**Comment by geertmeersman** [comment]
+1

**Comment by cyberjunky** [comment]
Which other integrations do you have installed? It looks like a conflict between two or more

**Comment by merc4derp** [comment]
> Which other integrations do you have installed? It looks like a conflict between two or more

From hacs only this and localtuya. Everything else is official and nothing too exotic.

**Comment by geertmeersman** [comment]
Errors gone in the 2023.10.0

**Comment by merc4derp** [comment]
Can confirm, no more errors after today's update. Closing this.
