### ISSUE TITLE
Feature: Implement 2FA functionality

### ISSUE THREAD

**Issue by cyberjunky** [cyberjunky/home-assistant-garmin_connect#117]
Placeholder for multiple related tickets

**Comment by Gawronnek** [comment]
I use the Mi Scale Exporter application on Android, the author Łukasz Świderski also had a problem with 2FA, but he managed to solve it, a window appears where we enter the received code, maybe he could tell us how to solve it in your application, he is a very kind man

**Comment by velaar** [comment]
Unfortunately Garmin now refuses to disable 2FA even via support request for any ECG-enabled watches. This might become more of a problem over time

**Comment by scar77** [comment]
According to Garmin, by law they are required to permanently enable 2FA on watches that have the ECG feature. Until this integration has 2FA capability those of us with newer Garmin watches sporting the ECG feature will not be able to integrate them in Home Assistant. Bummer.

**Comment by cyberjunky** [comment]
It's the same Garmin who keep their API closed sourced and thus didn't help when I asked them for access to their developers program, that's a Bummer too... But all kidding aside adding this functionality to the integration is still on the top of my list.

**Comment by RAYs3T** [comment]
Also just hit this issue. But it seems like the package used in the backgroud [Garth](https://pypi.org/project/garth/) already supports 2FA.
But looks like it tries to read the code from the pipe/std

Exception when login is tried with enabled 2FA:
```Traceback (most recent call last):
  File "/config/custom_components/garmin_connect/config_flow.py", line 47, in async_step_user
    await self.hass.async_add_executor_job(api.login)
  File "/usr/local/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/garminconnect/__init__.py", line 179, in login
    self.garth.login(self.username, self.password)
  File "/usr/local/lib/python3.11/site-packages/garth/http.py", line 160, in login
    self.oauth1_token, self.oauth2_token = sso.login(*args, client=self)
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/garth/sso.py", line 95, in login
    handle_mfa(client, SIGNIN_PARAMS)
  File "/usr/local/lib/python3.11/site-packages/garth/sso.py", line 147, in handle_mfa
    mfa_code = input("Enter MFA code: ")
               ^^^^^^^^^^^^^^^^^^^^^^^^^
EOFError: EOF when reading a line```

**Comment by velaar** [comment]
So all we are missing is an interface to enter the 2fa code? Looks like garth is already requesting it. I tried to hack my way around it but so far no luck.

**Comment by cyberjunky** [comment]
First we need to make sure we gather and store the oauth tokens in HA after login to account/reauth, and use that for future logins, so ditch the password storage. (there are two ways, store in a file, or in a string in HA storage, the last one is preferred)
Then fiddle with new version of Garth (separate branch) where we can set the callback routine to handle MFA (if user has it enabled)
See here https://github.com/matin/garth/issues/41
Then look into things like reauth flow when token has expired.
I'm looking into how the standard way of HA handling with oauth works (and handling a few of the above items) 
And trying to free up some time to work on it

**Comment by matin** [comment]
> there are two ways, store in a file, or in a string in HA storage, the last one is preferred

I recommend using [`Client.dumps()`](https://github.com/matin/garth/blob/main/garth/http.py#L201-L206) and [`Client.loads()`](https://github.com/matin/garth/blob/main/garth/http.py#L218-L224) if you're looking for a way to dump and load the tokens as a base64 encoded string. There are a few projects that use this method vs storing the tokens in files in environment variables.

> Then look into things like reauth flow when token has expired.

fwiw, the tokens generated after MFA are valid for one year 😁

**Comment by obhammer** [comment]
You really need to fix this asap. Garmin is getting more and more aggressive to ‘demand’ 2FA these days. I just bought a dashcam that CANNOT be used without 2FA, rendering my watch integration in HA useless 🤷🏼‍♂️ And all newer watch models with ECG is having the same limitation - meaning that more and more HA users will drop out…

**Comment by craigrouse** [comment]
@obhammer this integration is kindly developed by @cyberjunky in his spare time. Contributions are welcome from anyone willing to help. Please be a little more considerate with your language - nobody "needs" to fix it, but if someone does take the time, then we will all be grateful.

**Comment by jmadejek** [comment]
> > @obhammer this integration is kindly developed by @cyberjunky in his spare time. Contributions are welcome from anyone willing to help. Please be a little more considerate with your language - nobody "needs" to fix it, but if someone does take the time, then we will all be grateful.
> 
> Well, the fact is that Garmin seem to force ‘all’ users to use 2FA pretty soon - and in that regard, this integration will be rendered useless for ‘all’ users. The word ‘need’ is of course very harsh to use - what I meant was ‘’maybe, if integration should stay relevant, you should evaluate if you maybe need to do something about it - soon….maybe’’ 😉

Any updates with 2FA?

**Comment by matin** [comment]
There was a delay due to waiting on [a change in garth](https://github.com/matin/garth/issues/41#issuecomment-2080935856), an underlying library. I just published the change that should allow this to move forward.

**Comment by Gawronnek** [comment]
I wrote earlier about the Mi Scale Exporter application for Android, author Łukasz Świderski, the author has already managed to do it so well that you don't even have to enter the code every time, maybe it would help with our problem

**Comment by matin** [comment]
@Gawronnek the Garmin integration for mi-scale-exporter is [based on Garth](https://github.com/lswiderski/mi-scale-exporter/issues/20#issuecomment-1737822669) 😉 

I left [an earlier comment](https://github.com/cyberjunky/home-assistant-garmin_connect/issues/117#issuecomment-1955208037) on how to avoid repeatedly entering the MFA code. The token generated during the login is valid for one year. It just needs to be stored and reused (instead of using username/password + MFA code).

**Comment by nardev** [comment]
@matin Good news.

**Comment by LsVzqz** [comment]
Does this mean the feature is coming soon? 😀 

I'm currently on a 1476 day step streak and use an input boolean to manually track whether I hit my 10k step goal for the day, otherwise, HA bombards me with reminder messages every hour past 8pm to finish my steps for the day.  It would be nice if HA knew how many steps I had without me manually setting the input boolean every day.

Cheers!

**Comment by Bretos** [comment]
Everybody, there is quite an easy workaround available and working.

If you take a look at underlying login function [here](https://github.com/cyberjunky/python-garminconnect/blob/master/garminconnect/__init__.py#L200) you'll notice that it already uses [garth](https://github.com/matin/garth) library. This is great not only because garth allows saving tokens, but also this integration already tries to load them! So, in summary to use this integration if you have 2FA enabled on your Garmin Connect account you need to:

1. save session tokens using garth. This is doable with some simple python code, for instance (install garth first, `pip install garth`:
```python
import garth
from getpass import getpass

email = input("Enter email address: ")
password = getpass("Enter password: ")
# If there's MFA, you'll be prompted during the login
garth.login(email, password)
garth.save("~/.garth")
```
this will generate and save your session tokens to `~/.garth` (a hidden directory directly in your home dir, tokens are valid for 1 year)

2. you need to make those tokens accessible by Home Assistant.
  2.1 if you're running Home Assistant in docker:
    * copy content of `~/.garth` to any place you desire
    * mount that directory in the container, eg `/srv/docks/hass/.garth:/config/.garth`
    * add an environment variable `GARMINTOKENS` to equal to the path inside container
  2.2 if you're running HASS anyhow else - add env variable `GARMINTOKENS` that points at the directory tokens are in
3. configure the integration as you would if you didn't have 2FA enabled - tokens will be used
4. PROFIT! it works

**Comment by nelbs** [comment]
awesome! Got it working 😀

FYI
I used [this custom integration](https://github.com/Athozs/hass-environment-variable) to add the environment variable to homeassistant in step 2.2

**Comment by RAYs3T** [comment]
I took a look at it and tried to add the MFA request to the config flow, but since the call from inside garth for the `prompt_mfa` is not async, this is getting tricky with the HA config flow. 

I have no real experience with the HA config flow, but there seems to be no easy way to show a new form over a "step" that is not yet finished. If anybody knows how, let me know and I put what I have into a PR.

My current approch is to start another async call that is waiting for input to the MFA field (with timeout), if given, the login continues.

**Comment by cyberjunky** [comment]
> I took a look at it and tried to add the MFA request to the config flow, but since the call from inside garth for the `prompt_mfa` is not async, this is getting tricky with the HA config flow.
> 
> I have no real experience with the HA config flow, but there seems to be no easy way to show a new form over a "step" that is not yet finished. If anybody knows how, let me know and I put what I have into a PR.
> 
> My current approch is to start another async call that is waiting for input to the MFA field (with timeout), if given, the login continues.

I also implemented this, and was stuck on same issue, I then asked Matin from garth to make the function async, and he did, but I didn't have time to proceed/test it, make sure you are on last version of garth (in manifest) I believe he implemented it in production version

**Comment by cyberjunky** [comment]
I'm not 100% sure, it is in main branch or a seperate one, he mentioned it in a closed issue on garths gh, with an unrelated subject, cant find it that quick

**Comment by RAYs3T** [comment]
Awesome found it in 0.4.46, I will try to implement it and give it another try now.

**Comment by RAYs3T** [comment]
Yeehh, nah, this is still going into a direction it should not. I asked matin if it would be possible to split the mfa request into a different method, as this would make our life way easier and would go hand in hand with the HA config flow.

https://github.com/matin/garth/issues/41#issuecomment-2346596817

**Comment by cyberjunky** [comment]
But keep in mind you somehow need to know when to ask for MFA and when not, not everyone will enable it.

**Comment by RAYs3T** [comment]
> Following the ha rules for config flow is always good yes, but I don't think we ever get it through to be official integration though. Done that with FireServiceRota once and kind of promised myself not to attempt it with another integration, it costed me 5 years of my life. When you made one part follow the strict rules and lint, another part got deprecated...Almost impossible...

I understand, but the idea I had to get this working with the `promt_mfa()` Callback would be super dirty and if interrupted could then force a restart of the HA instance to get it working again, and it would also depend on a timer function.

I think we should implement a clean solution or otherwise use the [workaround with the GARMINTOKENS](https://github.com/cyberjunky/home-assistant-garmin_connect/issues/117#issuecomment-2343454775) as mentioned by Bretos.

I would love to have this implemented in a proper and stable way, even if this never makes it officially into HA, since it uses a closed API and is against the guidelines.

**Comment by cyberjunky** [comment]
Yeah. I agree. And yes more stable and following latest code structure is also what my aim is... And there are many many more sensors available then implemented in HA integration, I would love to implement categories of sensors to be enable/disabled by user, or autodetected

**Comment by jacobrian** [comment]
Workaround by Bretos definitely works. I just set it up, also used the custom integration by Melba to add the ENV variable.

**Comment by kirkoff71** [comment]
> 2\. GARMINTOKENS

You can make a guide step to step?
Now I have install Environment Variable, and garminconnect
Start garmin connect and make login> login error with mail from garmin with passcode.
in configuration mail insert this:

default_config:

environment_variable:
  GARMINTOKENS: 2911xxx

restart the home assistant

reloging garminconnect, but whit error.

Thanks

**Comment by kirkoff71** [comment]
> awesome! Got it working 😀
> 
> FYI I used [this custom integration](https://github.com/Athozs/hass-environment-variable) to add the environment variable to homeassistant in step 2.2

You can make a guide step to step?
Now I have install Environment Variable, and garminconnect
Start garmin connect and make login> login error with mail from garmin with passcode.
in configuration mail insert this:

default_config:

environment_variable:
GARMINTOKENS: 2911xxx

restart the home assistant

reloging garminconnect, but whit error.

Thanks

**Comment by nelbs** [comment]
The value for GARMINTOKENS should be the path to the folder where the tokens are stored, not the passkey you received.

**Comment by kirkoff71** [comment]
> The value for GARMINTOKENS should be the path to the folder where the tokens are stored, not the passkey you received.

Ok thanks, 
Then, for example, in the configuration.yaml insert:

`default_config:
environment_variable:
  GARMINTOKENS: /config/.passcode

And in config folder create a file ".passcode" with inside:

`123456`  In this case the code received from garmin?
Thanks

**Comment by kirkoff71** [comment]
> @kirkoff71 nope, inside directory `.passcode` put the tokens (two files) which were created by the python script I pasted in my [comment](https://github.com/cyberjunky/home-assistant-garmin_connect/issues/117#issuecomment-2343454775)

I have insert in configuration file this:

`environment_variable:
  GARMINTOKENS: /config/.passcode`

in the /config/.passcode have create a file "passcode_garmin.py" and copy inside this code:

`import garth
from getpass import getpass

email = input("Enter email address: ")
password = getpass("Enter password: ")
# If there's MFA, you'll be prompted during the login
garth.login(email, password)
garth.save("~/.garth")`


And anoter file ".garth" with inside the code recieved via mail correct?

**Comment by LsVzqz** [comment]
>     6. open the terminal and install "garth" with this command `pip install garth`
> 
>     7. In terminal change directory with this command: `cd /config/.passcode`
> 
>     8. Lunch the script: `python garmin.py` and insert, the mail, the password and the passcode send via mail from Garmin

Hello!  In my terminal, I don't have the pip command, nor python.  How would I get that installed?  I'm using HAOS..

**Comment by kirkoff71** [comment]
> > ```
> > 6. open the terminal and install "garth" with this command `pip install garth`
> > 
> > 7. In terminal change directory with this command: `cd /config/.passcode`
> > 
> > 8. Lunch the script: `python garmin.py` and insert, the mail, the password and the passcode send via mail from Garmin
> > ```
> 
> Hello! In my terminal, I don't have the pip command, nor python. How would I get that installed? I'm using HAOS..

Try install also python script from here:

https://www.home-assistant.io/integrations/python_script/

Waiting feedback because if ok add ad tutorial.

**Comment by ErazorVIP** [comment]
Hello,
can someone help me to get it running? 
I installed the HACS the 2Environment Variable. But on Step 3 i dont know where to find the "config.yaml"??
And if i try "pip install garth" i get this:
"bash: pip: command not found"

I using Home Assistant OS 13.1

**Comment by cowboyrushforth** [comment]
Small update on above - using multiple accounts, and the GARMINTOKENS workaround.  I made a few edits to the code, if anyone is interested I can put them in a branch, but they are a little hacky, and will go away if proper MFA support is added.

Ultimately, I added a new config option: vol.Optional(CONF_TOKENSTORE): str,}, and pass this into the login function as needed, so this is used instead of GARMINTOKENS.  This allows one to setup multiple config entries, with their own tokenstores.  

Which in turn, allows one to run the python script above per use you want to use, and save in a different area, and pass these areas separately to the ha config.

**Comment by nardev** [comment]
Great work guys. I just hope they will implement "pull data" so that i don't need to open the app to sync the steps.

**Comment by nelbs** [comment]
Are you sure your path is correct? In most comments the path begins with /config instead of /Homeassistant.

And did you installed the environmental variable integration?

**Comment by sinanqasha** [comment]
> Are you sure your path is correct? In most comments the path begins with /config instead of /Homeassistant.
> 
> And did you installed the environmental variable integration?

Is config the main directory where your configuration.yaml lives? 

I don't have a config/ directory on my main. I have homeassistant/ should create config/.passcode/garmin.py? In this case it would look like this homeassistant/config/.passcode/garmin.py

**Comment by sinanqasha** [comment]
Hello again,

Maybe this workaround does't work for virtual machine instalation? I was wondering if any one had input on this. @Bretos mentions that there are 2 ways one for docker and one for any other type of instalation.

The logs shows this error 
FileNotFoundError: [Errno 2] No such file or directory: '/homeassistant/.passcode/.garth/oauth1_token.json'
The file and the directory both exist and is exactly the same path in the erro logs.

**Comment by cjt-uk** [comment]
Is there any hope of 2FA being supported soon, or are the above workarounds the only hope to try for the foreseeable future?

**Comment by cyberjunky** [comment]
The underlying lib used called Garth is supporting MFA, my python example script from my python-garminconnect package who uses Garth works with MFA. But this is synchronous code, while
Home Assistant config flow is async, and I ran into issue with this a while back. I having another look at this as we speak.

**Comment by djfjeff** [comment]
Thanks for checking this out, now with Garmin releasing ECG more broadly, more customers are required to enable 2FA on their Garmin account.

**Comment by sapeur3873** [comment]
i did the explanation but i have all the time the same fault 

Traceback (most recent call last):
  File "/config/custom_components/garmin_connect/config_flow.py", line 47, in async_step_user
    await self.hass.async_add_executor_job(api.login)
  File "/usr/local/lib/python3.13/concurrent/futures/thread.py", line 59, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.13/site-packages/garminconnect/__init__.py", line 233, in login
    self.garth.load(tokenstore)
    ~~~~~~~~~~~~~~~^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/garth/http.py", line 218, in load
    with open(os.path.join(dir_path, "oauth1_token.json")) as f:
         ~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/util/loop.py", line 200, in protected_loop_func
    return func(*args, **kwargs)
FileNotFoundError: [Errno 2] No such file or directory: '/homeassistant/config/.passcode/.garth/oauth1_token.json'

i already try to change.
the file directory with 
config/.passcode/.garth
/config/.passcode/.garth
homeassistant/config/.passcode/.garth
/homeassistant/config/.passcode/.garth
config/.passcode/.garth/

i have all the time the same result.

on the directory /homeassistant/config/.passcode/.garth/ i have oauth1_token.json and oauth2_token.json.

i don't know what to do

**Comment by D3r3k23** [comment]
I was able to sign in using Garth, but then after rebooting the server it's asking for a code again. Does it normally keep you signed in after rebooting?

**Comment by jacobrian** [comment]
> I was able to sign in using Garth, but then after rebooting the server it's asking for a code again. Does it normally keep you signed in after rebooting?

Mine does the same thing. If you relaunch the integration after a reboot, it'll use the global variable. Setup an automation to reboot the integration 30 seconds after a bootup and just ignore the SMS.

**Comment by Imperial-Guard** [comment]
@cyberjunky Hi Ron, hope you're doing well, I was wondering if you had you had any update? I saw that you had some changes on the API Wrapper (Garmin Connect). 

Thanks!

**Comment by cyberjunky** [comment]
Hi All, I have created a pre-release beta version with native working MFA support, at least for me it does ;-) So no workarounds needed.

The oauth tokens get stored your passwords aren't.

Feel free to test it. 
You should be able to select it manually... go to HACS -> Garmin Connect -> Download and select the beta version from the dropdown.


Other than MFA only cosmetic things changed (logging and some error checking), so you should be able to go back and forth if needed.

![Image](https://github.com/user-attachments/assets/5734ccac-d94d-4a5c-ab7b-c5f3fed3240d)

**Comment by cyberjunky** [comment]
Note Updating from 0.2.30 to beta release not working. First need to remove accounts and uninstall integration and setup beta cleanly.

**Comment by Bretos** [comment]
1. remove existing integration instances (Garmin Connect accounts)
2. remove latest integration (HACS or `custom_components/` dir
3. restart HASS
4. install BETA
5. setup integration
6. profit

confirmed working. Thanks!

**Comment by cyberjunky** [comment]
I will see if I can create a version where migration works, otherwise a lot of people have issues updating when this goes out of beta

**Comment by PauloGoncalves86** [comment]
Worked fine for me as well, thanks!

**Comment by Gawronnek** [comment]
Worked fine for me as well, thanks!

**Comment by gurumusch** [comment]
I also tried it with a fresh ha docker install and it works fine for me. Thanks!

**Comment by cyberjunky** [comment]
Release 0.2.31-beta-04 should be able to upgrade from non mfa version, well it asks for reauth nicely once (to store oauth token instead of password) If anyone can test please.

**Comment by neebski** [comment]
> Release 0.2.31-beta-04 should be able to upgrade from non mfa version, well it asks for reauth nicely once (to store oauth token instead of password) If anyone can test please.

Works great for me. Thanks for the fix!

**Comment by m2726** [comment]
> Release 0.2.31-beta-04 should be able to upgrade from non mfa version, well it asks for reauth nicely once (to store oauth token instead of password) If anyone can test please.

Works fine for me, too. Thanks a lot.

**Comment by LsVzqz** [comment]
I downloaded 0.2.31-beta-04, restarted HA, added the garmin integration and it went through the wizard.  When I went to add username and password, I got this error and the following is from the log.


![Image](https://github.com/user-attachments/assets/e5653c4f-ec34-4479-801e-2ebc3f5218dd)


This error originated from a custom integration.

Logger: custom_components.garmin_connect.config_flow
Source: custom_components/garmin_connect/config_flow.py:59
integration: garmin_connect (documentation, issues)
First occurred: 9:15:33 PM (2 occurrences)
Last logged: 9:15:47 PM

Unexpected exception
Traceback (most recent call last):
  File "/config/custom_components/garmin_connect/config_flow.py", line 59, in _async_garmin_connect_login
    self._login_result1, self._login_result2 = await self.hass.async_add_executor_job(self._api.login)
                                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/concurrent/futures/thread.py", line 59, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.13/site-packages/garminconnect/__init__.py", line 231, in login
    self.garth.load(tokenstore)
    ~~~~~~~~~~~~~~~^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/garth/http.py", line 225, in load
    with open(os.path.join(dir_path, "oauth1_token.json")) as f:
         ~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/util/loop.py", line 201, in protected_loop_func
    return func(*args, **kwargs)
FileNotFoundError: [Errno 2] No such file or directory: '/config/.passcode/.garth/oauth1_token.json'

**Comment by cyberjunky** [comment]
It seems you still have the MFA workaround active, you need to remove all those settings, (including the env stuff) this path in the error is not part of my code.

**Comment by LsVzqz** [comment]
> It seems you still have the MFA workaround active, you need to remove all those settings, (including the env stuff) this path in the error is not part of my code.

You're right, I thought I removed it all, but missed something.  Cleaned it out, and it worked great! Thanks.

**Comment by liambresnahan** [comment]
Are there any plans to release this change please?

**Comment by Bretos** [comment]
It's implemented already in the BETA release since 0.2.31-beta-01.

**Comment by liambresnahan** [comment]
I meant release to the release channel

**Comment by cyberjunky** [comment]
I will have a look, my friend HA devs must have changed something in latest version, AGAIN.

**Comment by cyberjunky** [comment]
Well to honest everything still works here, on 2025.06.1 tried beta-01 and beta-04, no issues..

**Comment by cyberjunky** [comment]
Ni problem, glad it worked, I will try to merge the mfa beta to production soon
