### ISSUE TITLE
Unknown error occurred during Garmin Connect login request

### ISSUE THREAD

**Issue by LukaszP2** [cyberjunky/home-assistant-garmin_connect#129]
After upgrade to HA 2024.2.0b2

```
  - Traceback (most recent call last):
  File "/config/custom_components/garmin_connect/__init__.py", line 82, in async_login
    await self.hass.async_add_executor_job(self._api.login)
  File "/usr/local/lib/python3.12/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/garminconnect/__init__.py", line 179, in login
    self.garth.login(self.username, self.password)
  File "/usr/local/lib/python3.12/site-packages/garth/http.py", line 160, in login
    self.oauth1_token, self.oauth2_token = sso.login(*args, client=self)
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/garth/sso.py", line 98, in login
    assert title == "Success"
AssertionError
```

**Comment by cyberjunky** [comment]
Do you have MFA enabled? If so please test latest beta version, see ticket #117 
Closing this one
