### ISSUE TITLE
Cannot setup Garmin Connect integration

### ISSUE THREAD

**Issue by BernieV1977** [cyberjunky/home-assistant-garmin_connect#20]
After updating my HA Core to 2012.12.3 it's not possible to setup the Garmin Connect integration. I tried a reinstall but that doesn't changed a thing.

I see this in my log:
2021-12-20 16:00:31 ERROR (MainThread) [homeassistant.components.sensor] Error adding entities for domain sensor with platform garmin_connect
Traceback (most recent call last):
  File "/home/homeassistant/.pyenv/versions/3.9.9/lib/python3.9/site-packages/homeassistant/helpers/entity_platform.py", line 382, in async_add_entities
    await asyncio.gather(*tasks)
  File "/home/homeassistant/.pyenv/versions/3.9.9/lib/python3.9/site-packages/homeassistant/helpers/entity_platform.py", line 613, in _async_add_entity
    await entity.add_to_platform_finish()
  File "/home/homeassistant/.pyenv/versions/3.9.9/lib/python3.9/site-packages/homeassistant/helpers/entity.py", line 748, in add_to_platform_finish
    self.async_write_ha_state()
  File "/home/homeassistant/.pyenv/versions/3.9.9/lib/python3.9/site-packages/homeassistant/helpers/entity.py", line 505, in async_write_ha_state
    self._async_write_ha_state()
  File "/home/homeassistant/.pyenv/versions/3.9.9/lib/python3.9/site-packages/homeassistant/helpers/entity.py", line 538, in _async_write_ha_state
    state = self._stringify_state()
  File "/home/homeassistant/.pyenv/versions/3.9.9/lib/python3.9/site-packages/homeassistant/helpers/entity.py", line 511, in _stringify_state
    if (state := self.state) is None:
  File "/mnt/dietpi_userdata/homeassistant/custom_components/garmin_connect/sensor.py", line 125, in state
    return round(value, 2)
TypeError: type str doesn't define __round__ method

I'm running HA Core on a Rpi2 with Debian BullsEye and Ptyhon 3.9.9

**Comment by cyberjunky** [comment]
Release 0.1.4 should work better.
