### ISSUE TITLE
"List index out of range" since Core 2024.12.4

### ISSUE THREAD

**Issue by waazdakka** [cyberjunky/home-assistant-garmin_connect#214]
Hello, 

The Garmin integration stopped working since Core 2024.12.4 :( I just updated the integration to 0.2.23 but I still have a "List index out of range" error.
Any clue?

Thanks!

**Comment by stephenwilley** [comment]
Same error on mine.  Paste from debug log below:

`2024-12-19 10:10:43.140 ERROR (MainThread) [custom_components.garmin_connect] Unexpected error fetching garmin_connect data
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 379, in _async_refresh
    self.data = await self._async_update_data()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/garmin_connect/__init__.py", line 202, in _async_update_data
    **body["dateWeightList"][0],
      ~~~~~~~~~~~~~~~~~~~~~~^^^
IndexError: list index out of range
2024-12-19 10:10:52.705 ERROR (MainThread) [custom_components.garmin_connect] Unexpected error fetching garmin_connect data
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 379, in _async_refresh
    self.data = await self._async_update_data()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/garmin_connect/__init__.py", line 202, in _async_update_data
    **body["dateWeightList"][0],
      ~~~~~~~~~~~~~~~~~~~~~~^^^
IndexError: list index out of range
2024-12-19 10:11:08.088 ERROR (MainThread) [custom_components.garmin_connect.config_flow] Unexpected exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.13/site-packages/garth/http.py", line 143, in request
    self.last_resp.raise_for_status()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/usr/local/lib/python3.13/site-packages/requests/models.py", line 1024, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 429 Client Error: Too Many Requests for url: https://sso.garmin.com/sso/signin?id=gauth-widget&embedWidget=true&gauthHost=https%3A%2F%2Fsso.garmin.com%2Fsso%2Fembed&service=https%3A%2F%2Fsso.garmin.com%2Fsso%2Fembed&source=https%3A%2F%2Fsso.garmin.com%2Fsso%2Fembed&redirectAfterAccountLoginUrl=https%3A%2F%2Fsso.garmin.com%2Fsso%2Fembed&redirectAfterAccountCreationUrl=https%3A%2F%2Fsso.garmin.com%2Fsso%2Fembed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/config/custom_components/garmin_connect/config_flow.py", line 47, in async_step_user
    await self.hass.async_add_executor_job(api.login)
  File "/usr/local/lib/python3.13/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.13/site-packages/garminconnect/__init__.py", line 235, in login
    self.garth.login(
    ~~~~~~~~~~~~~~~~^
        self.username, self.password, prompt_mfa=self.prompt_mfa
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/usr/local/lib/python3.13/site-packages/garth/http.py", line 164, in login
    self.oauth1_token, self.oauth2_token = sso.login(
                                           ~~~~~~~~~^
        *args, **kwargs, client=self
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/usr/local/lib/python3.13/site-packages/garth/sso.py", line 127, in login
    client.post(
    ~~~~~~~~~~~^
        "sso",
        ^^^^^^
    ...<8 lines>...
        ),
        ^^
    )
    ^
  File "/usr/local/lib/python3.13/site-packages/garth/http.py", line 155, in post
    return self.request("POST", *args, **kwargs)
           ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/garth/http.py", line 145, in request
    raise GarthHTTPError(
    ...<2 lines>...
    )
garth.exc.GarthHTTPError: Error in request: 429 Client Error: Too Many Requests for url: https://sso.garmin.com/sso/signin?id=gauth-widget&embedWidget=true&gauthHost=https%3A%2F%2Fsso.garmin.com%2Fsso%2Fembed&service=https%3A%2F%2Fsso.garmin.com%2Fsso%2Fembed&source=https%3A%2F%2Fsso.garmin.com%2Fsso%2Fembed&redirectAfterAccountLoginUrl=https%3A%2F%2Fsso.garmin.com%2Fsso%2Fembed&redirectAfterAccountCreationUrl=https%3A%2F%2Fsso.garmin.com%2Fsso%2Fembed
2024-12-19 10:11:19.434 ERROR (MainThread) [custom_components.garmin_connect.config_flow] Unexpected exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.13/site-packages/garth/http.py", line 143, in request
    self.last_resp.raise_for_status()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/usr/local/lib/python3.13/site-packages/requests/models.py", line 1024, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 429 Client Error: Too Many Requests for url: https://sso.garmin.com/sso/signin?id=gauth-widget&embedWidget=true&gauthHost=https%3A%2F%2Fsso.garmin.com%2Fsso%2Fembed&service=https%3A%2F%2Fsso.garmin.com%2Fsso%2Fembed&source=https%3A%2F%2Fsso.garmin.com%2Fsso%2Fembed&redirectAfterAccountLoginUrl=https%3A%2F%2Fsso.garmin.com%2Fsso%2Fembed&redirectAfterAccountCreationUrl=https%3A%2F%2Fsso.garmin.com%2Fsso%2Fembed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/config/custom_components/garmin_connect/config_flow.py", line 47, in async_step_user
    await self.hass.async_add_executor_job(api.login)
  File "/usr/local/lib/python3.13/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.13/site-packages/garminconnect/__init__.py", line 235, in login
    self.garth.login(
    ~~~~~~~~~~~~~~~~^
        self.username, self.password, prompt_mfa=self.prompt_mfa
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/usr/local/lib/python3.13/site-packages/garth/http.py", line 164, in login
    self.oauth1_token, self.oauth2_token = sso.login(
                                           ~~~~~~~~~^
        *args, **kwargs, client=self
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/usr/local/lib/python3.13/site-packages/garth/sso.py", line 127, in login
    client.post(
    ~~~~~~~~~~~^
        "sso",
        ^^^^^^
    ...<8 lines>...
        ),
        ^^
    )
    ^
  File "/usr/local/lib/python3.13/site-packages/garth/http.py", line 155, in post
    return self.request("POST", *args, **kwargs)
           ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/garth/http.py", line 145, in request
    raise GarthHTTPError(
    ...<2 lines>...
    )
garth.exc.GarthHTTPError: Error in request: 429 Client Error: Too Many Requests for url: https://sso.garmin.com/sso/signin?id=gauth-widget&embedWidget=true&gauthHost=https%3A%2F%2Fsso.garmin.com%2Fsso%2Fembed&service=https%3A%2F%2Fsso.garmin.com%2Fsso%2Fembed&source=https%3A%2F%2Fsso.garmin.com%2Fsso%2Fembed&redirectAfterAccountLoginUrl=https%3A%2F%2Fsso.garmin.com%2Fsso%2Fembed&redirectAfterAccountCreationUrl=https%3A%2F%2Fsso.garmin.com%2Fsso%2Fembed
2024-12-19 10:11:51.508 ERROR (MainThread) [custom_components.garmin_connect] Unexpected error fetching garmin_connect data
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 379, in _async_refresh
    self.data = await self._async_update_data()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/garmin_connect/__init__.py", line 202, in _async_update_data
    **body["dateWeightList"][0],
      ~~~~~~~~~~~~~~~~~~~~~~^^^
IndexError: list index out of range
2024-12-19 10:12:01.531 ERROR (MainThread) [custom_components.garmin_connect] Unexpected error fetching garmin_connect data
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 379, in _async_refresh
    self.data = await self._async_update_data()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/garmin_connect/__init__.py", line 202, in _async_update_data
    **body["dateWeightList"][0],
      ~~~~~~~~~~~~~~~~~~~~~~^^^
IndexError: list index out of range
2024-12-19 10:12:13.412 ERROR (MainThread) [custom_components.garmin_connect] Unknown error occurred during Garmin Connect login request
Traceback (most recent call last):
  File "/usr/local/lib/python3.13/site-packages/garth/http.py", line 143, in request
    self.last_resp.raise_for_status()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/usr/local/lib/python3.13/site-packages/requests/models.py", line 1024, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 429 Client Error: Too Many Requests for url: https://sso.garmin.com/sso/signin?id=gauth-widget&embedWidget=true&gauthHost=https%3A%2F%2Fsso.garmin.com%2Fsso%2Fembed&service=https%3A%2F%2Fsso.garmin.com%2Fsso%2Fembed&source=https%3A%2F%2Fsso.garmin.com%2Fsso%2Fembed&redirectAfterAccountLoginUrl=https%3A%2F%2Fsso.garmin.com%2Fsso%2Fembed&redirectAfterAccountCreationUrl=https%3A%2F%2Fsso.garmin.com%2Fsso%2Fembed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/config/custom_components/garmin_connect/__init__.py", line 82, in async_login
    await self.hass.async_add_executor_job(self._api.login)
  File "/usr/local/lib/python3.13/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.13/site-packages/garminconnect/__init__.py", line 235, in login
    self.garth.login(
    ~~~~~~~~~~~~~~~~^
        self.username, self.password, prompt_mfa=self.prompt_mfa
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/usr/local/lib/python3.13/site-packages/garth/http.py", line 164, in login
    self.oauth1_token, self.oauth2_token = sso.login(
                                           ~~~~~~~~~^
        *args, **kwargs, client=self
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/usr/local/lib/python3.13/site-packages/garth/sso.py", line 127, in login
    client.post(
    ~~~~~~~~~~~^
        "sso",
        ^^^^^^
    ...<8 lines>...
        ),
        ^^
    )
    ^
  File "/usr/local/lib/python3.13/site-packages/garth/http.py", line 155, in post
    return self.request("POST", *args, **kwargs)
           ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/garth/http.py", line 145, in request
    raise GarthHTTPError(
    ...<2 lines>...
    )
garth.exc.GarthHTTPError: Error in request: 429 Client Error: Too Many Requests for url: https://sso.garmin.com/sso/signin?id=gauth-widget&embedWidget=true&gauthHost=https%3A%2F%2Fsso.garmin.com%2Fsso%2Fembed&service=https%3A%2F%2Fsso.garmin.com%2Fsso%2Fembed&source=https%3A%2F%2Fsso.garmin.com%2Fsso%2Fembed&redirectAfterAccountLoginUrl=https%3A%2F%2Fsso.garmin.com%2Fsso%2Fembed&redirectAfterAccountCreationUrl=https%3A%2F%2Fsso.garmin.com%2Fsso%2Fembed
`

**Comment by cyberjunky** [comment]
Do you have MFA enabled, is password correct? One error is related to no data I can fix that, but it's probably due to the errors below it

**Comment by cyberjunky** [comment]
And if you revert back to older version everything works again?

**Comment by stephenwilley** [comment]
Checked password with connect.garmin.com - it is indeed correct. MFA is not enabled.
Reverting to previous version works fine.

**Comment by jonathanjsimon** [comment]
I also have this problem

**Comment by nckslater** [comment]
Same issue

**Comment by waazdakka** [comment]
Hello,
So I first downgraded the integration which works totally fine on 0.2.23, then upgraded again to 0.2.24 and then I get this error:
`Enregistreur: custom_components.garmin_connect
Source: helpers/update_coordinator.py:379
intégration: Garmin Connect (documentation, problèmes)
S'est produit pour la première fois: 23:26:12 (7 occurrences)
Dernier enregistrement: 23:30:55

Unexpected error fetching garmin_connect data
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 379, in _async_refresh
    self.data = await self._async_update_data()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/garmin_connect/__init__.py", line 202, in _async_update_data
    **body["dateWeightList"][0],
      ~~~~~~~~~~~~~~~~~~~~~~^^^
IndexError: list index out of range`

And I just noticed you forgot to update the version number! :)
<img width="281" alt="image" src="https://github.com/user-attachments/assets/4eb70951-60d9-42d5-b8fe-f53fc86cdb38" />

**Comment by cyberjunky** [comment]
Thank you all for reporting, I made some fixes, values which seem to be different sometimes, perhaps linked to Garmin devices used or not.
Can you try version 0.2.25?

**Comment by daalja** [comment]
Thanks a lot cyberjunky,

with 0.2.25 it seems to be fixed.
