### ISSUE TITLE
login but no data

### ISSUE THREAD

**Issue by StefanoA70** [cyberjunky/home-assistant-garmin_connect#25]
After updating to the latest version login seems to be fine but I don't see any data from my garmin account,
all 81 entities listed are in "unavailable" status

**Comment by cyberjunky** [comment]
@StefanoA70 After a restart this can happen, you will see a forbidden url message, i'm looking into this.
But this resolves itself after a minute or so, if it doesn't for you please enable debugging to see what is going on.

**Comment by StefanoA70** [comment]
These are the items containing "Garmin" from the log after server restart:

2022-01-05 07:20:12 WARNING (SyncWorker_4) [homeassistant.loader] We found a custom integration garmin_connect which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant

2022-01-05 07:20:21 INFO (MainThread) [homeassistant.bootstrap] Setting up stage 2: {'history', 'binary_sensor', 'dhcp', 'garmin_connect', 'xiaomi_gateway3', 'zeroconf', 'blueprint', 'met', 'input_text', 'hacs', 'default_config', 'dlna_dmr', 'counter', 'group', 'rpi_power', 'my', 'timer', 'xiaomi_miio', 'input_boolean', 'input_datetime', 'updater', 'network', 'energy', 'utility_meter', 'input_select', 'logbook', 'scene', 'automation', 'climacell', 'media_source', 'ssdp', 'upnp', 'input_number', 'sun', 'sensor', 'airvisual', 'openweathermap', 'mobile_app', 'script', 'zone', 'tts', 'xiaomi_miot_raw', 'tag', 'system_health', 'trace', 'persistent_notification', 'usb', 'map'}

2022-01-05 07:20:21 INFO (MainThread) [homeassistant.setup] Setting up garmin_connect
2022-01-05 07:20:21 INFO (MainThread) [homeassistant.setup] Setup of domain garmin_connect took 0.0 seconds

2022-01-05 07:20:56 DEBUG (MainThread) [custom_components.garmin_connect] Finished fetching garmin_connect data in 5.382 seconds (success: True)
2022-01-05 07:20:56 INFO (MainThread) [homeassistant.components.sensor] Setting up sensor.garmin_connect
2022-01-05 07:20:56 DEBUG (MainThread) [custom_components.garmin_connect.sensor] Registering entity: totalSteps, Total Steps, steps, mdi:walk, None, True
2022-01-05 07:20:56 DEBUG (MainThread) [custom_components.garmin_connect.sensor] Registering entity: dailyStepGoal, Daily Step Goal, steps, mdi:walk, None, True
2022-01-05 07:20:56 DEBUG (MainThread) [custom_components.garmin_connect.sensor] Registering entity: totalKilocalories, Total KiloCalories, kcal, mdi:food, None, True
2

now it's 7:35 and all 81 entities of the "Garmin Connect" device are in UNKNOWN status

**Comment by StefanoA70** [comment]
more debug data (now entities are in UNAVAILABLE status)

2022-01-05 07:36:20 INFO (MainThread) [homeassistant.components.analytics] Submitted analytics to Home Assistant servers. Information submitted includes {'uuid': '434b3c2f274c4ff4a4943a4cb065bcdc', 'version': '2021.12.7', 'installation_type': 'Home Assistant Supervised', 'supervisor': {'healthy': True, 'supported': False, 'arch': 'armv7'}, 'integrations': ['history', 'recorder', 'blueprint', 'counter', 'fan', 'group', 'image', 'search', 'input_select', 'config', 'filter', 'media_source', 'openweathermap', 'mobile_app', 'tag', 'select', 'alarm_control_panel', 'persistent_notification', 'map', 'statistics', 'workday', 'default_config', 'my', 'xiaomi_miio', 'cover', 'input_datetime', 'onboarding', 'updater', 'energy', 'utility_meter', 'homeassistant', 'logbook', 'climacell', 'automation', 'ssdp', 'tts', 'remote', 'number', 'trace', 'frontend', 'device_automation', 'person', 'notify', 'system_log', 'input_text', 'webhook', 'vacuum', 'dlna_dmr', 'auth', 'climate', 'switch', 'media_player', 'network', 'analytics', 'scene', 'upnp', 'stream', 'websocket_api', 'sun', 'zone', 'sensor', 'airvisual', 'script', 'usb', 'template', 'binary_sensor', 'dhcp', 'zeroconf', 'met', 'lock', 'logger', 'hassio', 'device_tracker', 'rpi_power', 'google_translate', 'cloud', 'timer', 'weather', 'input_boolean', 'light', 'input_number', 'api', 'lovelace', 'system_health', 'http'], 'custom_integrations': [{'domain': 'garmin_connect', 'version': <AwesomeVersion SemVer '0.1.8'>}, {'domain': 'average', 'version': <AwesomeVersion SemVer '2.2.0'>}, {'domain': 'xiaomi_miot_raw', 'version': <AwesomeVersion SemVer '1.3.1'>}, {'domain': 'xiaomi_gateway3', 'version': <AwesomeVersion SemVer '1.6.5'>}, {'domain': 'hacs', 'version': <AwesomeVersion SemVer '1.18.0'>}], 'addons': [{'slug': 'core_duckdns', 'protected': True, 'version': '1.14.0', 'auto_update': False}, {'slug': 'core_configurator', 'protected': True, 'version': '5.3.3', 'auto_update': True}, {'slug': 'core_ssh', 'protected': True, 'version': '9.2.2', 'auto_update': False}], 'energy': {'configured': False}, 'state_count': 254, 'automation_count': 0, 'integration_count': 85, 'addon_count': 3, 'user_count': 2}

2022-01-05 07:42:08 ERROR (MainThread) [custom_components.garmin_connect] Unexpected error fetching garmin_connect data: local variable 'response' referenced before assignment
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 445, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "/usr/local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 440, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/local/lib/python3.9/http/client.py", line 1371, in getresponse
    response.begin()
  File "/usr/local/lib/python3.9/http/client.py", line 319, in begin
    version, status, reason = self._read_status()
  File "/usr/local/lib/python3.9/http/client.py", line 280, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/usr/local/lib/python3.9/socket.py", line 704, in readinto
    return self._sock.recv_into(b)
  File "/usr/local/lib/python3.9/ssl.py", line 1241, in recv_into
    return self.read(nbytes, buffer)
  File "/usr/local/lib/python3.9/ssl.py", line 1099, in read
    return self._sslobj.read(len, buffer)
TimeoutError: [Errno 110] Operation timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
  File "/usr/local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 755, in urlopen
    retries = retries.increment(
  File "/usr/local/lib/python3.9/site-packages/urllib3/util/retry.py", line 532, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/usr/local/lib/python3.9/site-packages/urllib3/packages/six.py", line 770, in reraise
    raise value
  File "/usr/local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 699, in urlopen
    httplib_response = self._make_request(
  File "/usr/local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 447, in _make_request
    self._raise_timeout(err=e, url=url, timeout_value=read_timeout)
  File "/usr/local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 353, in _raise_timeout
    raise ReadTimeoutError(
urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='connect.garmin.com', port=443): Read timed out. (read timeout=None)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/garminconnect/__init__.py", line 47, in get
    response = self.session.get(url, headers=total_headers, params=params)
  File "/usr/local/lib/python3.9/site-packages/requests/sessions.py", line 555, in get
    return self.request('GET', url, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/cloudscraper/__init__.py", line 263, in request
    self.perform_request(method, url, *args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/cloudscraper/__init__.py", line 182, in perform_request
    return super(CloudScraper, self).request(method, url, *args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.9/site-packages/requests/sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/requests/adapters.py", line 529, in send
    raise ReadTimeout(e, request=request)
requests.exceptions.ReadTimeout: HTTPSConnectionPool(host='connect.garmin.com', port=443): Read timed out. (read timeout=None)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 187, in _async_refresh
    self.data = await self._async_update_data()
  File "/config/custom_components/garmin_connect/__init__.py", line 93, in _async_update_data
    summary = await self.hass.async_add_executor_job(
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.9/site-packages/garminconnect/__init__.py", line 309, in get_user_summary
    response = self.modern_rest_client.get(url, params=params).json()
  File "/usr/local/lib/python3.9/site-packages/garminconnect/__init__.py", line 51, in get
    if response.status_code == 429:
UnboundLocalError: local variable 'response' referenced before assignment
2022-01-05 07:42:09 DEBUG (MainThread) [custom_components.garmin_connect] Finished fetching garmin_connect data in 973.029 seconds (success: False)

2022-01-05 07:42:09 DEBUG (MainThread) [custom_components.garmin_connect] Finished fetching garmin_connect data in 973.029 seconds (success: False)

2022-01-05 08:03:23 ERROR (MainThread) [custom_components.garmin_connect] Unexpected error fetching garmin_connect data: local variable 'response' referenced before assignment
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 445, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "/usr/local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 440, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/local/lib/python3.9/http/client.py", line 1371, in getresponse
    response.begin()
  File "/usr/local/lib/python3.9/http/client.py", line 319, in begin
    version, status, reason = self._read_status()
  File "/usr/local/lib/python3.9/http/client.py", line 280, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/usr/local/lib/python3.9/socket.py", line 704, in readinto
    return self._sock.recv_into(b)
  File "/usr/local/lib/python3.9/ssl.py", line 1241, in recv_into
    return self.read(nbytes, buffer)
  File "/usr/local/lib/python3.9/ssl.py", line 1099, in read
    return self._sslobj.read(len, buffer)
TimeoutError: [Errno 110] Operation timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
  File "/usr/local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 755, in urlopen
    retries = retries.increment(
  File "/usr/local/lib/python3.9/site-packages/urllib3/util/retry.py", line 532, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/usr/local/lib/python3.9/site-packages/urllib3/packages/six.py", line 770, in reraise
    raise value
  File "/usr/local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 699, in urlopen
    httplib_response = self._make_request(
  File "/usr/local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 447, in _make_request
    self._raise_timeout(err=e, url=url, timeout_value=read_timeout)
  File "/usr/local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 353, in _raise_timeout
    raise ReadTimeoutError(
urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='connectus.garmin.cn', port=443): Read timed out. (read timeout=None)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/garminconnect/__init__.py", line 47, in get
    response = self.session.get(url, headers=total_headers, params=params)
  File "/usr/local/lib/python3.9/site-packages/requests/sessions.py", line 555, in get
    return self.request('GET', url, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/cloudscraper/__init__.py", line 263, in request
    self.perform_request(method, url, *args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/cloudscraper/__init__.py", line 182, in perform_request
    return super(CloudScraper, self).request(method, url, *args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.9/site-packages/requests/sessions.py", line 677, in send
    history = [resp for resp in gen]
  File "/usr/local/lib/python3.9/site-packages/requests/sessions.py", line 677, in <listcomp>
    history = [resp for resp in gen]
  File "/usr/local/lib/python3.9/site-packages/requests/sessions.py", line 237, in resolve_redirects
    resp = self.send(
  File "/usr/local/lib/python3.9/site-packages/requests/sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/requests/adapters.py", line 529, in send
    raise ReadTimeout(e, request=request)
requests.exceptions.ReadTimeout: HTTPSConnectionPool(host='connectus.garmin.cn', port=443): Read timed out. (read timeout=None)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 187, in _async_refresh
    self.data = await self._async_update_data()
  File "/config/custom_components/garmin_connect/__init__.py", line 93, in _async_update_data
    summary = await self.hass.async_add_executor_job(
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.9/site-packages/garminconnect/__init__.py", line 309, in get_user_summary
    response = self.modern_rest_client.get(url, params=params).json()
  File "/usr/local/lib/python3.9/site-packages/garminconnect/__init__.py", line 51, in get
    if response.status_code == 429:
UnboundLocalError: local variable 'response' referenced before assignment
2022-01-05 08:03:23 DEBUG (MainThread) [custom_components.garmin_connect] Finished fetching garmin_connect data in 974.850 seconds (success: False)

**Comment by cyberjunky** [comment]
Closing old ticket, error 429 means rate limit exceeded, which can happen when to many retries in short time have been executed.
