### ISSUE TITLE
State max length is 255 characters.

### ISSUE THREAD

**Issue by allanpersson** [cyberjunky/home-assistant-garmin_connect#3]
File "/usr/src/homeassistant/homeassistant/core.py", line 1218, in async_set
    state = State(
      File "/usr/src/homeassistant/homeassistant/core.py", line 906, in __init__
          raise InvalidStateError(
          homeassistant.exceptions.InvalidStateError: Invalid state encountered for entity ID: sensor.garmin_next_alarm. State max length is 255 characters.

**Comment by allanpersson** [comment]
## System Health

version | core-2021.7.3
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
virtualenv | false
python_version | 3.9.5
os_name | Linux
os_version | 5.10.45
arch | x86_64
timezone | Europe/Copenhagen

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
Github API Calls Remaining | 4744
Installed Version | 1.13.2
Stage | running
Available Repositories | 926
Installed Repositories | 37

</details>

<details><summary>AccuWeather</summary>

can_reach_server | ok
-- | --
remaining_requests | 10

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | true
-- | --
subscription_expiration | August 18, 2021, 02:00
relayer_connected | true
remote_enabled | true
remote_connected | true
alexa_enabled | true
google_enabled | true
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 6.1
-- | --
update_channel | stable
supervisor_version | supervisor-2021.06.8
docker_version | 20.10.6
disk_total | 468.8 GB
disk_used | 25.9 GB
healthy | true
supported | true
board | generic-x86-64
supervisor_api | ok
version_api | ok
installed_addons | Home Assistant Google Drive Backup (0.104.3), SSH & Web Terminal (9.0.0), UniFi Controller (0.23.2), FTP (4.2.0), Log Viewer (0.11.1), Glances (0.12.3), Mosquitto broker (6.0.1), Visual Studio Code (3.6.0), ESPHome (1.19.4), Samba share (9.5.1)

</details>

<details><summary>Lovelace</summary>

dashboards | 14
-- | --
resources | 31
views | 52
mode | storage

</details>

<details><summary>Spotify</summary>

api_endpoint_reachable | ok
-- | --

</details>

**Comment by cyberjunky** [comment]
Hi Alan, how many alarms did you have configured?

**Comment by allanpersson** [comment]
Either none or one (i have never had more than one).
And in both cases it throws same error

**Comment by cyberjunky** [comment]
Are you able to enable debug, and post the relevant part from the log? Specially the json data containing alarms and the error details. Without exposing any private data.

**Comment by allanpersson** [comment]
I will have a look at it first in next week :)
Can you paste the relevant services i have to enable debug for?

**Comment by cyberjunky** [comment]
Thanks.

Just this or last part of it if you have some lines already.

```
logger:
  default: info
  logs:
    custom_components.garmin_connect: debug
    garminconnect_ha: debug
```

**Comment by allanpersson** [comment]
**Lines excluded due to lot of personal informations**
2021-08-22 22:21:52 DEBUG (SyncWorker_37) [garminconnect_ha] Gathering device alarms
2021-08-22 22:21:52 DEBUG (SyncWorker_37) [garminconnect_ha] Requesting devices with URL: https://connect.garmin.com/proxy/device-service/deviceregistration/devices
2021-08-22 22:21:53 DEBUG (SyncWorker_37) [garminconnect_ha] Response status code: 200
**Lines excluded due to lot of personal informations**
2021-08-22 22:21:53 DEBUG (MainThread) [custom_components.garmin_connect] Finished fetching garmin_connect data in 1.147 seconds
2021-08-22 22:21:53 DEBUG (MainThread) [custom_components.garmin_connect.sensor] Registering entity: totalSteps, Total Steps, steps, mdi:walk, None, True
2021-08-22 22:21:53 DEBUG (MainThread) [custom_components.garmin_connect.sensor] Registering entity: dailyStepGoal, Daily Step Goal, steps, mdi:walk, None, True
2021-08-22 22:21:53 DEBUG (MainThread) [custom_components.garmin_connect.sensor] Registering entity: totalKilocalories, Total KiloCalories, kcal, mdi:food, None, True
2021-08-22 22:21:53 DEBUG (MainThread) [custom_components.garmin_connect.sensor] Registering entity: activeKilocalories, Active KiloCalories, kcal, mdi:food, None, True
2021-08-22 22:21:53 DEBUG (MainThread) [custom_components.garmin_connect.sensor] Registering entity: bmrKilocalories, BMR KiloCalories, kcal, mdi:food, None, True
2021-08-22 22:21:53 DEBUG (MainThread) [custom_components.garmin_connect.sensor] Registering entity: consumedKilocalories, Consumed KiloCalories, kcal, mdi:food, None, False
2021-08-22 22:21:53 DEBUG (MainThread) [custom_components.garmin_connect.sensor] Registering entity: burnedKilocalories, Burned KiloCalories, kcal, mdi:food, None, True
2021-08-22 22:21:53 DEBUG (MainThread) [custom_components.garmin_connect.sensor] Registering entity: remainingKilocalories, Remaining KiloCalories, kcal, mdi:food, None, False
2021-08-22 22:21:53 DEBUG (MainThread) [custom_components.garmin_connect.sensor] Registering entity: netRemainingKilocalories, Net Remaining KiloCalories, kcal, mdi:food, None, False
2021-08-22 22:21:53 DEBUG (MainThread) [custom_components.garmin_connect.sensor] Registering entity: netCalorieGoal, Net Calorie Goal, cal, mdi:food, None, False
2021-08-22 22:21:53 DEBUG (MainThread) [custom_components.garmin_connect.sensor] Registering entity: totalDistanceMeters, Total Distance Mtr, m, mdi:walk, None, True
2021-08-22 22:21:53 DEBUG (MainThread) [custom_components.garmin_connect.sensor] Registering entity: wellnessStartTimeLocal, Wellness Start Time, None, mdi:clock, timestamp, False
2021-08-22 22:21:53 DEBUG (MainThread) [custom_components.garmin_connect.sensor] Registering entity: wellnessEndTimeLocal, Wellness End Time, None, mdi:clock, timestamp, False
2021-08-22 22:21:53 DEBUG (MainThread) [custom_components.garmin_connect.sensor] Registering entity: wellnessDescription, Wellness Description, , mdi:clock, None, False
2021-08-22 22:21:53 DEBUG (MainThread) [custom_components.garmin_connect.sensor] Registering entity: wellnessDistanceMeters, Wellness Distance Mtr, m, mdi:walk, None, False
2021-08-22 22:21:53 DEBUG (MainThread) [custom_components.garmin_connect.sensor] Registering entity: wellnessActiveKilocalories, Wellness Active KiloCalories, kcal, mdi:food, None, False
2021-08-22 22:21:53 DEBUG (MainThread) [custom_components.garmin_connect.sensor] Registering entity: wellnessKilocalories, Wellness KiloCalories, kcal, mdi:food, None, False
2021-08-22 22:21:53 DEBUG (MainThread) [custom_components.garmin_connect.sensor] Registering entity: highlyActiveSeconds, Highly Active Time, min, mdi:fire, None, False
2021-08-22 22:21:53 DEBUG (MainThread) [custom_components.garmin_connect.sensor] Registering entity: activeSeconds, Active Time, min, mdi:fire, None, True
2021-08-22 22:21:53 DEBUG (MainThread) [custom_components.garmin_connect.sensor] Registering entity: sedentarySeconds, Sedentary Time, min, mdi:seat, None, True
2021-08-22 22:21:53 DEBUG (MainThread) [custom_components.garmin_connect.sensor] Registering entity: sleepingSeconds, Sleeping Time, min, mdi:sleep, None, True
2021-08-22 22:21:53 DEBUG (MainThread) [custom_components.garmin_connect.sensor] Registering entity: measurableAwakeDuration, Awake Duration, min, mdi:sleep, None, True
2021-08-22 22:21:53 DEBUG (MainThread) [custom_components.garmin_connect.sensor] Registering entity: measurableAsleepDuration, Sleep Duration, min, mdi:sleep, None, True
2021-08-22 22:21:53 DEBUG (MainThread) [custom_components.garmin_connect.sensor] Registering entity: floorsAscendedInMeters, Floors Ascended Mtr, m, mdi:stairs, None, False
2021-08-22 22:21:53 DEBUG (MainThread) [custom_components.garmin_connect.sensor] Registering entity: floorsDescendedInMeters, Floors Descended Mtr, m, mdi:stairs, None, False
2021-08-22 22:21:53 DEBUG (MainThread) [custom_components.garmin_connect.sensor] Registering entity: floorsAscended, Floors Ascended, floors, mdi:stairs, None, True
2021-08-22 22:21:53 DEBUG (MainThread) [custom_components.garmin_connect.sensor] Registering entity: floorsDescended, Floors Descended, floors, mdi:stairs, None, True
2021-08-22 22:21:53 DEBUG (MainThread) [custom_components.garmin_connect.sensor] Registering entity: userFloorsAscendedGoal, Floors Ascended Goal, floors, mdi:stairs, None, True
2021-08-22 22:21:53 DEBUG (MainThread) [custom_components.garmin_connect.sensor] Registering entity: minHeartRate, Min Heart Rate, bpm, mdi:heart-pulse, None, True
2021-08-22 22:21:53 DEBUG (MainThread) [custom_components.garmin_connect.sensor] Registering entity: maxHeartRate, Max Heart Rate, bpm, mdi:heart-pulse, None, True
2021-08-22 22:21:53 DEBUG (MainThread) [custom_components.garmin_connect.sensor] Registering entity: restingHeartRate, Resting Heart Rate, bpm, mdi:heart-pulse, None, True
2021-08-22 22:21:53 DEBUG (MainThread) [custom_components.garmin_connect.sensor] Registering entity: minAvgHeartRate, Min Avg Heart Rate, bpm, mdi:heart-pulse, None, False
2021-08-22 22:21:53 DEBUG (MainThread) [custom_components.garmin_connect.sensor] Registering entity: maxAvgHeartRate, Max Avg Heart Rate, bpm, mdi:heart-pulse, None, False
2021-08-22 22:21:53 DEBUG (MainThread) [custom_components.garmin_connect.sensor] Registering entity: abnormalHeartRateAlertsCount, Abnormal HR Counts, None, mdi:heart-pulse, None, False
2021-08-22 22:21:53 DEBUG (MainThread) [custom_components.garmin_connect.sensor] Registering entity: lastSevenDaysAvgRestingHeartRate, Last 7 Days Avg Heart Rate, bpm, mdi:heart-pulse, None, False
2021-08-22 22:21:53 DEBUG (MainThread) [custom_components.garmin_connect.sensor] Registering entity: averageStressLevel, Avg Stress Level, lvl, mdi:flash-alert, None, True
2021-08-22 22:21:53 DEBUG (MainThread) [custom_components.garmin_connect.sensor] Registering entity: maxStressLevel, Max Stress Level, lvl, mdi:flash-alert, None, True
2021-08-22 22:21:53 DEBUG (MainThread) [custom_components.garmin_connect.sensor] Registering entity: stressQualifier, Stress Qualifier, None, mdi:flash-alert, None, False
2021-08-22 22:21:53 DEBUG (MainThread) [custom_components.garmin_connect.sensor] Registering entity: stressDuration, Stress Duration, min, mdi:flash-alert, None, False
2021-08-22 22:21:53 DEBUG (MainThread) [custom_components.garmin_connect.sensor] Registering entity: restStressDuration, Rest Stress Duration, min, mdi:flash-alert, None, True
2021-08-22 22:21:53 DEBUG (MainThread) [custom_components.garmin_connect.sensor] Registering entity: activityStressDuration, Activity Stress Duration, min, mdi:flash-alert, None, True
2021-08-22 22:21:53 DEBUG (MainThread) [custom_components.garmin_connect.sensor] Registering entity: uncategorizedStressDuration, Uncat. Stress Duration, min, mdi:flash-alert, None, True
2021-08-22 22:21:53 DEBUG (MainThread) [custom_components.garmin_connect.sensor] Registering entity: totalStressDuration, Total Stress Duration, min, mdi:flash-alert, None, True
2021-08-22 22:21:53 DEBUG (MainThread) [custom_components.garmin_connect.sensor] Registering entity: lowStressDuration, Low Stress Duration, min, mdi:flash-alert, None, True
2021-08-22 22:21:53 DEBUG (MainThread) [custom_components.garmin_connect.sensor] Registering entity: mediumStressDuration, Medium Stress Duration, min, mdi:flash-alert, None, True
2021-08-22 22:21:53 DEBUG (MainThread) [custom_components.garmin_connect.sensor] Registering entity: highStressDuration, High Stress Duration, min, mdi:flash-alert, None, True
2021-08-22 22:21:53 DEBUG (MainThread) [custom_components.garmin_connect.sensor] Registering entity: stressPercentage, Stress Percentage, %, mdi:flash-alert, None, False
2021-08-22 22:21:53 DEBUG (MainThread) [custom_components.garmin_connect.sensor] Registering entity: restStressPercentage, Rest Stress Percentage, %, mdi:flash-alert, None, False
2021-08-22 22:21:53 DEBUG (MainThread) [custom_components.garmin_connect.sensor] Registering entity: activityStressPercentage, Activity Stress Percentage, %, mdi:flash-alert, None, False
2021-08-22 22:21:53 DEBUG (MainThread) [custom_components.garmin_connect.sensor] Registering entity: uncategorizedStressPercentage, Uncat. Stress Percentage, %, mdi:flash-alert, None, False
2021-08-22 22:21:53 DEBUG (MainThread) [custom_components.garmin_connect.sensor] Registering entity: lowStressPercentage, Low Stress Percentage, %, mdi:flash-alert, None, False
2021-08-22 22:21:53 DEBUG (MainThread) [custom_components.garmin_connect.sensor] Registering entity: mediumStressPercentage, Medium Stress Percentage, %, mdi:flash-alert, None, False
2021-08-22 22:21:53 DEBUG (MainThread) [custom_components.garmin_connect.sensor] Registering entity: highStressPercentage, High Stress Percentage, %, mdi:flash-alert, None, False
2021-08-22 22:21:53 DEBUG (MainThread) [custom_components.garmin_connect.sensor] Registering entity: moderateIntensityMinutes, Moderate Intensity, min, mdi:flash-alert, None, False
2021-08-22 22:21:53 DEBUG (MainThread) [custom_components.garmin_connect.sensor] Registering entity: vigorousIntensityMinutes, Vigorous Intensity, min, mdi:run-fast, None, False
2021-08-22 22:21:53 DEBUG (MainThread) [custom_components.garmin_connect.sensor] Registering entity: intensityMinutesGoal, Intensity Goal, min, mdi:run-fast, None, False
2021-08-22 22:21:53 DEBUG (MainThread) [custom_components.garmin_connect.sensor] Registering entity: bodyBatteryChargedValue, Body Battery Charged, %, mdi:battery-charging-100, None, True
2021-08-22 22:21:53 DEBUG (MainThread) [custom_components.garmin_connect.sensor] Registering entity: bodyBatteryDrainedValue, Body Battery Drained, %, mdi:battery-alert-variant-outline, None, True
2021-08-22 22:21:53 DEBUG (MainThread) [custom_components.garmin_connect.sensor] Registering entity: bodyBatteryHighestValue, Body Battery Highest, %, mdi:battery-heart, None, True
2021-08-22 22:21:53 DEBUG (MainThread) [custom_components.garmin_connect.sensor] Registering entity: bodyBatteryLowestValue, Body Battery Lowest, %, mdi:battery-heart-outline, None, True
2021-08-22 22:21:53 DEBUG (MainThread) [custom_components.garmin_connect.sensor] Registering entity: bodyBatteryMostRecentValue, Body Battery Most Recent, %, mdi:battery-positive, None, True
2021-08-22 22:21:53 DEBUG (MainThread) [custom_components.garmin_connect.sensor] Registering entity: averageSpo2, Average SPO2, %, mdi:diabetes, None, True
2021-08-22 22:21:53 DEBUG (MainThread) [custom_components.garmin_connect.sensor] Registering entity: lowestSpo2, Lowest SPO2, %, mdi:diabetes, None, True
2021-08-22 22:21:53 DEBUG (MainThread) [custom_components.garmin_connect.sensor] Registering entity: latestSpo2, Latest SPO2, %, mdi:diabetes, None, True
2021-08-22 22:21:53 DEBUG (MainThread) [custom_components.garmin_connect.sensor] Registering entity: latestSpo2ReadingTimeLocal, Latest SPO2 Time, None, mdi:diabetes, timestamp, False
2021-08-22 22:21:53 DEBUG (MainThread) [custom_components.garmin_connect.sensor] Registering entity: averageMonitoringEnvironmentAltitude, Average Altitude, %, mdi:image-filter-hdr, None, False
2021-08-22 22:21:53 DEBUG (MainThread) [custom_components.garmin_connect.sensor] Registering entity: highestRespirationValue, Highest Respiration, brpm, mdi:progress-clock, None, False
2021-08-22 22:21:53 DEBUG (MainThread) [custom_components.garmin_connect.sensor] Registering entity: lowestRespirationValue, Lowest Respiration, brpm, mdi:progress-clock, None, False
2021-08-22 22:21:53 DEBUG (MainThread) [custom_components.garmin_connect.sensor] Registering entity: latestRespirationValue, Latest Respiration, brpm, mdi:progress-clock, None, False
2021-08-22 22:21:53 DEBUG (MainThread) [custom_components.garmin_connect.sensor] Registering entity: latestRespirationTimeGMT, Latest Respiration Update, None, mdi:progress-clock, timestamp, False
2021-08-22 22:21:53 DEBUG (MainThread) [custom_components.garmin_connect.sensor] Registering entity: weight, Weight, kg, mdi:weight-kilogram, None, False
2021-08-22 22:21:53 DEBUG (MainThread) [custom_components.garmin_connect.sensor] Registering entity: bmi, BMI, bmi, mdi:food, None, False
2021-08-22 22:21:53 DEBUG (MainThread) [custom_components.garmin_connect.sensor] Registering entity: bodyFat, Body Fat, %, mdi:food, None, False
2021-08-22 22:21:53 DEBUG (MainThread) [custom_components.garmin_connect.sensor] Registering entity: bodyWater, Body Water, %, mdi:water-percent, None, False
2021-08-22 22:21:53 DEBUG (MainThread) [custom_components.garmin_connect.sensor] Registering entity: bodyMass, Body Mass, kg, mdi:food, None, False
2021-08-22 22:21:53 DEBUG (MainThread) [custom_components.garmin_connect.sensor] Registering entity: muscleMass, Muscle Mass, kg, mdi:dumbbell, None, False
2021-08-22 22:21:53 DEBUG (MainThread) [custom_components.garmin_connect.sensor] Registering entity: physiqueRating, Physique Rating, None, mdi:numeric, None, False
2021-08-22 22:21:53 DEBUG (MainThread) [custom_components.garmin_connect.sensor] Registering entity: visceralFat, Visceral Fat, %, mdi:food, None, False
2021-08-22 22:21:53 DEBUG (MainThread) [custom_components.garmin_connect.sensor] Registering entity: metabolicAge, Metabolic Age, y, mdi:calendar-heart, None, False
2021-08-22 22:21:53 DEBUG (MainThread) [custom_components.garmin_connect.sensor] Registering entity: nextAlarm, Next Alarm Time, None, mdi:alarm, timestamp, True
2021-08-22 22:21:53 ERROR (MainThread) [homeassistant.components.sensor] Error adding entities for domain sensor with platform garmin_connect
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 382, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 587, in _async_add_entity
    await entity.add_to_platform_finish()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 711, in add_to_platform_finish
    self.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 464, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 590, in _async_write_ha_state
    self.hass.states.async_set(
  File "/usr/src/homeassistant/homeassistant/core.py", line 1218, in async_set
    state = State(
  File "/usr/src/homeassistant/homeassistant/core.py", line 906, in __init__
    raise InvalidStateError(
homeassistant.exceptions.InvalidStateError: Invalid state encountered for entity ID: sensor.next_alarm_time. State max length is 255 characters.
2021-08-22 22:21:53 ERROR (MainThread) [homeassistant.components.sensor] Error while setting up garmin_connect platform for sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 257, in _async_setup_platform
    await asyncio.gather(*pending)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 382, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 587, in _async_add_entity
    await entity.add_to_platform_finish()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 711, in add_to_platform_finish
    self.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 464, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 590, in _async_write_ha_state
    self.hass.states.async_set(
  File "/usr/src/homeassistant/homeassistant/core.py", line 1218, in async_set
    state = State(
  File "/usr/src/homeassistant/homeassistant/core.py", line 906, in __init__
    raise InvalidStateError(
homeassistant.exceptions.InvalidStateError: Invalid state encountered for entity ID: sensor.next_alarm_time. State max length is 255 characters.

**Comment by allanpersson** [comment]
``
2021-08-28 20:47:18 DEBUG (SyncWorker_34) [garminconnect_ha] Response: [{"appSupport":true,"applicationKey":"forerunner935","deviceTypePk":34216,"bestInClassVideoLink":null,"bluetoothClassicDevice":false,"bluetoothLowEnergyDevice":true,"deviceCategories":["FITNESS","WELLNESS","GOLF","OUTDOOR"],"deviceEmbedVideoLink":null,"deviceSettingsFile":"Forerunner935.json","gcmSettingsFile":null,"deviceVideoPageLink":null,"displayOrder":0,"golfDisplayOrder":0,"hasOpticalHeartRate":true,"highlighted":false,"hybrid":true,"imageUrl":"https://static.garmincdn.com/com.garmin.connect/content/images/device-images/forerunner-935.png","minGCMAndroidVersion":2250,"minGCMWindowsVersion":0,"minGCMiOSVersion":450,"minGolfAppiOSVersion":0,"minGolfAppAndroidVersion":0,"partNumber":"006-B2691-00","primary":true,"productDisplayName":"Forerunner 935","deviceTags":null,"productSku":"010-01746-04","wasp":false,"weightScale":false,"wellness":false,"wifi":true,"hasPowerButton":true,"supportsSecondaryUsers":false,"abnormalHeartRateAlertCapable":true,"activitySummFitFileCapable":true,"aerobicTrainingEffectCapable":true,"alarmDaysCapable":true,"allDayStressCapable":true,"anaerobicTrainingEffectCapable":true,"atpWorkoutCapable":true,"bodyBatteryCapable":false,"brickWorkoutCapable":true,"cardioCapable":true,"cardioOptionCapable":false,"cardioSportsCapable":false,"cardioWorkoutCapable":true,"cellularCapable":false,"changeLogCapable":true,"contactManagementCapable":false,"courseCapable":true,"courseFileType":"FIT","coursePromptCapable":false,"customIntensityMinutesCapable":false,"customWorkoutCapable":true,"cyclingSegmentCapable":true,"cyclingSportsCapable":false,"cyclingWorkoutCapable":true,"defaultSettingCapable":true,"deviceSettingCapable":true,"deviceSettingFileType":null,"displayFieldsExtCapable":false,"divingCapable":false,"ellipticalOptionCapable":false,"floorsClimbedGoalCapable":true,"ftpCapable":true,"gcj02CourseCapable":false,"glonassCapable":false,"goalCapable":true,"goalFileType":"FIT","golfAppSyncCapable":false,"gpsRouteCapable":true,"handednessCapable":true,"hrZoneCapable":true,"hrvStressCapable":true,"intensityMinutesGoalCapable":true,"lactateThresholdCapable":true,"languageSettingCapable":false,"languageSettingFileType":null,"lowHrAlertCapable":false,"maxHRCapable":true,"maxWorkoutCount":200,"metricsFitFileReceiveCapable":true,"metricsUploadCapable":true,"militaryTimeCapable":false,"moderateIntensityMinutesGoalCapable":true,"nfcCapable":false,"otherOptionCapable":false,"otherSportsCapable":false,"personalRecordCapable":true,"personalRecordFileType":"FIT","poolSwimOptionCapable":false,"powerCurveCapable":false,"powerZonesCapable":true,"pulseOxAllDayCapable":false,"pulseOxOnDemandCapable":false,"pulseOxSleepCapable":false,"remCapable":true,"reminderAlarmCapable":false,"reorderablePagesCapable":false,"restingHRCapable":true,"rideOptionsCapable":false,"runOptionIndoorCapable":false,"runOptionsCapable":false,"runningSegmentCapable":true,"runningSportsCapable":false,"runningWorkoutCapable":true,"scheduleCapable":true,"scheduleFileType":"FIT","segmentCapable":true,"segmentPointCapable":true,"settingCapable":true,"settingFileType":"FIT","sleepTimeCapable":true,"smallFitFileOnlyCapable":false,"sportCapable":true,"sportFileType":"FIT","stairStepperOptionCapable":false,"strengthOptionsCapable":false,"strengthWorkoutCapable":true,"supportedHrZones":["RUNNING","CYCLING","SWIMMING","ALL"],"swimWorkoutCapable":true,"trainingPlanCapable":true,"trainingStatusCapable":true,"trainingStatusPauseCapable":false,"userProfileCapable":false,"userProfileFileType":null,"userTcxExportCapable":false,"vo2MaxBikeCapable":true,"vo2MaxRunCapable":true,"walkOptionCapable":false,"walkingSportsCapable":false,"weatherAlertsCapable":false,"weatherSettingsCapable":false,"workoutCapable":true,"workoutFileType":"FIT","yogaCapable":false,"yogaOptionCapable":false,"heatAndAltitudeAcclimationCapable":false,"trainingLoadBalanceCapable":false,"indoorTrackOptionsCapable":false,"indoorBikeOptionsCapable":false,"indoorWalkOptionsCapable":false,"trainingEffectLabelCapable":false,"pacebandCapable":false,"respirationCapable":false,"openWaterSwimOptionCapable":false,"phoneVerificationCheckRequired":false,"weightGoalCapable":false,"yogaWorkoutCapable":false,"pilatesWorkoutCapable":false,"connectedGPSCapable":false,"diveAppSyncCapable":false,"golfLiveScoringCapable":false,"bloodEfficiencySleepCapable":false,"bloodEfficiencyAllDayCapable":false,"bloodEfficiencyOnDemandCapable":false,"solarPanelUtilizationCapable":false,"sweatLossCapable":false,"diveAlertCapable":false,"requiresInitialDeviceNickname":false,"defaultSettingsHbaseMigrated":false,"sleepScoreCapable":false,"fitnessAgeV2Capable":false,"intensityMinutesV2Capable":false,"collapsibleControlMenuCapable":false,"measurementUnitSettingCapable":false,"onDeviceSleepCalculationCapable":false,"hiitWorkoutCapable":false,"runningHeartRateZoneCapable":true,"cyclingHeartRateZoneCapable":true,"swimmingHeartRateZoneCapable":true,"defaultHeartRateZoneCapable":true,"cyclingPowerZonesCapable":true,"xcSkiPowerZonesCapable":false,"swimAlgorithmCapable":true,"benchmarkExerciseCapable":false,"spectatorMessagingCapable":false,"ecgCapable":false,"lteLiveEventSharingCapable":false,"sleepFitFileReceiveCapable":false,"secondaryWorkoutStepTargetCapable":false,"assistancePlusCapable":false,"powerGuidanceCapable":false,"airIntegrationCapable":false,"healthSnapshotCapable":false,"racePredictionsRunCapable":false,"vivohubCompatible":false,"stepsTrueUpChartCapable":false,"sportingEventCapable":false,"solarChargeCapable":false,"realTimeSettingsCapable":false,"emergencyCallingCapable":false,"personalRepRecordCapable":false,"hrvStatusCapable":false,"trainingReadinessCapable":false,"datasource":"C","deviceStatus":"active","registeredDate":1588609415000,"actualProductSku":"010-01746-04","vivohubConfigurable":null,"serialNumber":"50S046346","shortName":null,"displayName":"Forerunner 935","unRetirable":false,"corporateDevice":false,"prePairedWithHRM":false,"unitId":3950858414,"deviceId":3950858414,"activeInd":1,"primaryActivityTrackerIndicator":true,"wifiSetup":false,"currentFirmwareVersionMajor":21,"currentFirmwareVersionMinor":0,"currentFirmwareVersion":"21.00","isPrimaryUser":false,"otherAssociation":false,"minCustomIntensityMinutesVersion":"0"}]
``
Correct?

**Comment by cyberjunky** [comment]
@allanpersson can you try release 0.1.2, it should fix the error when you have no alarm set.

**Comment by allanpersson** [comment]
It seems like it's fixed in the new version. Thanks for your effort 👏
