### ISSUE TITLE
Data retrieval/parsing cancelled due to exception with "Wellness start time" sensor enabled

### ISSUE THREAD

**Issue by Broekman** [cyberjunky/home-assistant-garmin_connect#46]
Data retrieval/parsing cancelled due to exception with Wellness start time sensor enabled.

- This value is empty in my Garmin Connect, however I just enabled everthing to see what was coming in.
- This was for me the only sensor giving troubles in the logs (had all sensors enabled previously).
- Home assistant says this sensor is no longer used by the Connect integration, however removing it and reloading the integration adds it back again.

`AttributeError: 'str' object has no attribute 'tzinfo'`

`ValueError: Invalid datetime: sensor.wellness_start_time has timestamp device class but provides state 2022-11-19T00:00:00.0:<class 'str'> resulting in ''str' object has no attribute 'tzinfo''`

- Since I don't use this value, I disabled the sensor for now which **for me resolves the issue,** but wanted to report it nevertheless.

Full log:
```
2022-11-19 18:50:07.471 DEBUG (MainThread) [custom_components.garmin_connect] Finished fetching garmin_connect data in 1.471 seconds (success: True)
2022-11-19 18:50:07.472 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
File "/usr/share/webapps/homeassistant/lib/python3.10/site-packages/homeassistant/components/sensor/__init__.py", line 678, in state
if value.tzinfo is None:
AttributeError: 'str' object has no attribute 'tzinfo'
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
File "/usr/share/webapps/homeassistant/lib/python3.10/site-packages/homeassistant/helpers/update_coordinator.py", line 151, in _handle_refresh_interval
await self._async_refresh(log_failures=True, scheduled=True)
File "/usr/share/webapps/homeassistant/lib/python3.10/site-packages/homeassistant/helpers/update_coordinator.py", line 283, in _async_refresh
self.async_update_listeners()
File "/usr/share/webapps/homeassistant/lib/python3.10/site-packages/homeassistant/helpers/update_coordinator.py", line 110, in async_update_listeners
update_callback()
File "/usr/share/webapps/homeassistant/lib/python3.10/site-packages/homeassistant/helpers/update_coordinator.py", line 348, in _handle_coordinator_update
self.async_write_ha_state()
File "/usr/share/webapps/homeassistant/lib/python3.10/site-packages/homeassistant/helpers/entity.py", line 545, in async_write_ha_state
self._async_write_ha_state()
File "/usr/share/webapps/homeassistant/lib/python3.10/site-packages/homeassistant/helpers/entity.py", line 583, in _async_write_ha_state
state = self._stringify_state(available)
File "/usr/share/webapps/homeassistant/lib/python3.10/site-packages/homeassistant/helpers/entity.py", line 551, in _stringify_state
if (state := self.state) is None:
File "/usr/share/webapps/homeassistant/lib/python3.10/site-packages/homeassistant/components/sensor/__init__.py", line 689, in state
raise ValueError(
ValueError: Invalid datetime: sensor.wellness_start_time has timestamp device class but provides state 2022-11-19T00:00:00.0:<class 'str'> resulting in ''str' object has no attribute 'tzinfo''
```

- Home Assistant core 2022.11.2
- Garmin Connect integration 0.2.1
- Phone: Google Pixel 6a (Android 13).
- Garmin Connect 4.61 on Android.
- Watch: Garmin Vivoactive 4

**Comment by cyberjunky** [comment]
Can you try version 0.2.3 it should still work with those sensors enabled.

**Comment by Broekman** [comment]
Hi @cyberjunky, just tried it with 0.2.3 and all works as expected, the value comes in nicely, thanks!

Closing this ticket right away.
