### ISSUE TITLE
Home Assistant 2023.1 gives an error on state class "total" for "timestamp" device class sensors

### ISSUE THREAD

**Issue by Broekman** [cyberjunky/home-assistant-garmin_connect#56]
Back again :)

Since Hass 2023.1 we now get an error on the Timestamp device class sensors  :)

For all these sensors (in sensor.py), the state class "total" is defined, however this assumes a numeric value. In case of all sensors with device class timestamp:
- Wellness start
- Wellness end
- Latest SPO2 time

Weirdly it isn't complaining about the following two, which also have this state + device class.
- Latest respiration update
- Next alarm time

Commit in December added this to Hass core:
https://github.com/home-assistant/core/commit/762eb576363af584c9e160b0bc61464d91e44e2d

As stated in the comment of the core code:
```
Sensors with device classes indicating a non-numeric value should not have a state class or unit of measurement.
```

Thanks, let me know if you need any additional information!

```
2023-01-07 00:29:44.246 ERROR (MainThread) [homeassistant.components.sensor] Error while setting up garmin_connect platform for sensor
Traceback (most recent call last):
File "/usr/share/webapps/homeassistant/lib/python3.10/site-packages/homeassistant/helpers/entity_platform.py", line 297, in _async_setup_platform
await asyncio.gather(*pending)
File "/usr/share/webapps/homeassistant/lib/python3.10/site-packages/homeassistant/helpers/entity_platform.py", line 438, in async_add_entities
await asyncio.gather(*tasks)
File "/usr/share/webapps/homeassistant/lib/python3.10/site-packages/homeassistant/helpers/entity_platform.py", line 709, in _async_add_entity
await entity.add_to_platform_finish()
File "/usr/share/webapps/homeassistant/lib/python3.10/site-packages/homeassistant/helpers/entity.py", line 804, in add_to_platform_finish
self.async_write_ha_state()
File "/usr/share/webapps/homeassistant/lib/python3.10/site-packages/homeassistant/helpers/entity.py", line 556, in async_write_ha_state
self._async_write_ha_state()
File "/usr/share/webapps/homeassistant/lib/python3.10/site-packages/homeassistant/helpers/entity.py", line 597, in _async_write_ha_state
state = self._stringify_state(available)
File "/usr/share/webapps/homeassistant/lib/python3.10/site-packages/homeassistant/helpers/entity.py", line 562, in _stringify_state
if (state := self.state) is None:
File "/usr/share/webapps/homeassistant/lib/python3.10/site-packages/homeassistant/components/sensor/__init__.py", line 901, in state
raise ValueError(
ValueError: Sensor sensor.wellness_start_time has a state class and thus indicating it has a numeric value; however, it has the non-numeric device class: timestamp
```

**Comment by cyberjunky** [comment]
Didn't know about the default value, thanks, I have fixed it in 0.2.7 can you test?

**Comment by Broekman** [comment]
Thanks for the change, the only one where we still need to remove the state class is latestSpo2, after that all work as expected.

**Comment by cyberjunky** [comment]
Can you try latest 0.2.8 version?

**Comment by Broekman** [comment]
All good with 0.2.8, thanks!
