### ISSUE TITLE
Other sensor errors in ha 2023.1.1

### ISSUE THREAD

**Issue by acdcnow** [cyberjunky/home-assistant-garmin_connect#59]
Logger: homeassistant.components.sensor
Source: components/sensor/__init__.py:901
Integration: Sensor (documentation, issues)
First occurred: January 7, 2023 at 07:18:09 (2 occurrences)
Last logged: January 7, 2023 at 07:18:11

Error adding entities for domain sensor with platform garmin_connect
Error while setting up garmin_connect platform for sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 438, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 709, in _async_add_entity
    await entity.add_to_platform_finish()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 804, in add_to_platform_finish
    self.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 556, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 597, in _async_write_ha_state
    state = self._stringify_state(available)
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 562, in _stringify_state
    if (state := self.state) is None:
  File "/usr/src/homeassistant/homeassistant/components/sensor/__init__.py", line 901, in state
    raise ValueError(
ValueError: Sensor sensor.next_alarm_time has a state class and thus indicating it has a numeric value; however, it has the non-numeric device class: timestamp

**Comment by djalexnl** [comment]
Exact same errors in my HA logging

**Comment by cyberjunky** [comment]
Thanks for reporting, can you try version 0.2.8?
Sorry for any inconvenience, was forced to update some code, because of deprecated parts, which triggered some bugs.

**Comment by acdcnow** [comment]
all working again thanks great work!
