### ISSUE TITLE
Unexpected Error when trying to login

### ISSUE THREAD

**Issue by wildmor** [cyberjunky/home-assistant-garmin_connect#83]
Hello,
I got "_Unexpected Error_" When I try to login to Garmin Connect.

Error code in LOGS:
_Traceback (most recent call last):
  File "/config/custom_components/garmin_connect/config_flow.py", line 47, in async_step_user
    await self.hass.async_add_executor_job(api.login)
  File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.10/site-packages/garminconnect/__init__.py", line 270, in login
    return self.authenticate()
  File "/usr/local/lib/python3.10/site-packages/garminconnect/__init__.py", line 403, in authenticate
    self.display_name = user_prefs["displayName"]
KeyError: 'displayName'_

I had Polish special character in my "Name" but i changed it in Garmin portal with no resoult.
Do I have to wait after changing or is it something other problem with?

**Comment by cyberjunky** [comment]
Closed because old, if still an issue please (re)open a ticket
