### ISSUE TITLE
Startup does not work

### ISSUE THREAD

**Issue by 8cH9azbsFifZ** [cyberjunky/home-assistant-garmin_connect#91]
2023-07-15 00:08:38.953 DEBUG (MainThread) [custom_components.garmin_connect] {'userProfileId': 65237898, 'displayName': 'd2bd7320-951c-49fe-8b7d-adfb6815470c', 'totalKilocalories': None, 'activeKilocalories': None, 'bmrKilocalories': None, 'wellnessKilocalories': None, 'burnedKilocalories': None, 'consumedKilocalories': None, 'remainingKilocalories': None, 'totalSteps': None, 'netCalorieGoal': None, 'totalDistanceMeters': None, 'wellnessDistanceMeters': None, 'wellnessActiveKilocalories': None, 'netRemainingKilocalories': 0.0, 'userDailySummaryId': None, 'calendarDate': '2023-07-15', 'rule': None, 'uuid': None, 'dailyStepGoal': None, 'wellnessStartTimeGmt': None, 'wellnessStartTimeLocal': None, 'wellnessEndTimeGmt': None, 'wellnessEndTimeLocal': None, 'durationInMilliseconds': None, 'wellnessDescription': None, 'highlyActiveSeconds': None, 'activeSeconds': None, 'sedentarySeconds': None, 'sleepingSeconds': None, 'includesWellnessData': False, 'includesActivityData': False, 'includesCalorieConsumedData': False, 'privacyProtected': False, 'moderateIntensityMinutes': None, 'vigorousIntensityMinutes': None, 'floorsAscendedInMeters': None, 'floorsDescendedInMeters': None, 'floorsAscended': None, 'floorsDescended': None, 'intensityMinutesGoal': None, 'userFloorsAscendedGoal': None, 'minHeartRate': None, 'maxHeartRate': None, 'restingHeartRate': None, 'lastSevenDaysAvgRestingHeartRate': None, 'source': 'GARMIN', 'averageStressLevel': None, 'maxStressLevel': None, 'stressDuration': None, 'restStressDuration': None, 'activityStressDuration': None, 'uncategorizedStressDuration': None, 'totalStressDuration': None, 'lowStressDuration': None, 'mediumStressDuration': None, 'highStressDuration': None, 'stressPercentage': None, 'restStressPercentage': None, 'activityStressPercentage': None, 'uncategorizedStressPercentage': None, 'lowStressPercentage': None, 'mediumStressPercentage': None, 'highStressPercentage': None, 'stressQualifier': None, 'measurableAwakeDuration': None, 'measurableAsleepDuration': None, 'lastSyncTimestampGMT': None, 'minAvgHeartRate': None, 'maxAvgHeartRate': None, 'bodyBatteryChargedValue': None, 'bodyBatteryDrainedValue': None, 'bodyBatteryHighestValue': None, 'bodyBatteryLowestValue': None, 'bodyBatteryMostRecentValue': None, 'bodyBatteryVersion': None, 'abnormalHeartRateAlertsCount': None, 'averageSpo2': None, 'lowestSpo2': None, 'latestSpo2': None, 'latestSpo2ReadingTimeGmt': None, 'latestSpo2ReadingTimeLocal': None, 'averageMonitoringEnvironmentAltitude': None, 'restingCaloriesFromActivity': None}
2023-07-15 00:08:40.814 DEBUG (MainThread) [custom_components.garmin_connect] {'startDate': '2023-07-15', 'endDate': '2023-07-15', 'dateWeightList': [], 'totalAverage': {'from': 1689379200000, 'until': 1689465599999, 'weight': None, 'bmi': None, 'bodyFat': None, 'bodyWater': None, 'boneMass': None, 'muscleMass': None, 'physiqueRating': None, 'visceralFat': None, 'metabolicAge': None}}
2023-07-15 00:08:42.676 DEBUG (MainThread) [custom_components.garmin_connect] [{'alarmMode': 'OFF', 'alarmTime': 375, 'alarmDays': ['ONCE'], 'alarmSound': 'TONE_AND_VIBRATION', 'alarmId': 1627423641, 'changeState': 'UNCHANGED', 'backlight': 'ON', 'enabled': None, 'alarmMessage': None, 'alarmImageId': None, 'alarmIcon': None, 'alarmType': None}, {'alarmMode': 'OFF', 'alarmTime': 331, 'alarmDays': ['ONCE'], 'alarmSound': 'TONE_AND_VIBRATION', 'alarmId': 1627854368, 'changeState': 'UNCHANGED', 'backlight': 'ON', 'enabled': None, 'alarmMessage': None, 'alarmImageId': None, 'alarmIcon': None, 'alarmType': None}, {'alarmMode': 'OFF', 'alarmTime': 391, 'alarmDays': ['ONCE'], 'alarmSound': 'TONE_AND_VIBRATION', 'alarmId': 1628026811, 'changeState': 'UNCHANGED', 'backlight': 'ON', 'enabled': None, 'alarmMessage': None, 'alarmImageId': None, 'alarmIcon': None, 'alarmType': None}]
2023-07-15 00:08:43.199 ERROR (MainThread) [custom_components.garmin_connect] Unexpected error fetching garmin_connect data: 'NoneType' object has no attribute 'json'
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 283, in _async_refresh
    self.data = await self._async_update_data()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/garmin_connect/__init__.py", line 129, in _async_update_data
    gear_stats = await asyncio.gather(*tasks)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/garminconnect/__init__.py", line 856, in get_gear_stats
    return self.modern_rest_client.get(url).json()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'json'
2023-07-15 00:08:43.255 DEBUG (MainThread) [custom_components.garmin_connect] Finished fetching garmin_connect data in 4.747 seconds (success: False)
2023-07-15 00:08:44.333 WARNING (SyncWorker_18) [urllib3.connectionpool] Connection pool is full, discarding connection: connect.garmin.com. Connection pool size: 10
2023-07-15 00:08:44.338 WARNING (SyncWorker_19) [urllib3.connectionpool] Connection pool is full, discarding connection: connect.garmin.com. Connection pool size: 10
2023-07-15 00:08:44.431 WARNING (SyncWorker_14) [urllib3.connectionpool] Connection pool is full, discarding connection: connect.garmin.com. Connection pool size: 10
2023-07-15 00:08:44.438 WARNING (SyncWorker_20) [urllib3.connectionpool] Connection pool is full, discarding connection: connect.garmin.com. Connection pool size: 10
2023-07-15 00:08:44.445 WARNING (SyncWorker_3) [urllib3.connectionpool] Connection pool is full, discarding connection: connect.garmin.com. Connection pool size: 10

**Comment by 8cH9azbsFifZ** [comment]
Seems like there is a missing check if returned variable emtpy in __init__.py. This is the workaround:

        
#tasks: list[Awaitable] = [
            #    self.hass.async_add_executor_job(
            #        self._api.get_gear_stats, gear_item[GEAR.UUID]
            #    )
            #    for gear_item in gear
            #]

**Comment by 8cH9azbsFifZ** [comment]
cf. https://github.com/cyberjunky/home-assistant-garmin_connect/pull/96

**Comment by cyberjunky** [comment]
@8cH9azbsFifZ Can you test of it works in latest version of the intergration (still without this PR)
